### ISSUE TITLE
Feature Request: Networked Item Box

### ISSUE THREAD

**Issue by RaiRaiTheRaichu** [FuzzyGamesOn/RE2R_AP_World#15]
Hi,

Sorry if this is considered out of scope, but I wanted to pass along a suggestion for allowing networked item boxes. I see the option for allowing generating items for multiple players, so I think being able to pass items back and forth would be a great enhancement.

The concept is something along these lines:

- Hook into the item box "open" function, check if no other players are accessing it, fetch the list of items from a central server, then show the menu.
- Allow the player to move items as normal from inventory to box, etc.
- Hook into the item box "close" function, forward the updated table of items to the server for all clients to receive when necessary.

A possible sticking point is the method of adding items to the item box directly as a player approaches the area and loads in an item box. Possible resolution would be waiting (re-attempting to add it to the item box every x seconds) to make sure nobody is in the item box menu, and then inserting it.

Would be extremely neat if _(in the long run)_ players could both play Leon and Claire's section side by side and pass the necessary items to each other via item box.

I'm not familiar enough with RE2R's engine and such to explain it in any more detail, but I'd appreciate the consideration regardless! ^~^

**Comment by FuzzyGamesOn** [comment]
I think what you're describing sounds cool as a mod in general. :smiley: 

Just doesn't seem like a good fit for a multiworld randomizer like this one. People don't share items in this but, instead, they're finding items in their world that either belong to them or belong to other players. So sharing items between item boxes in this would reduce the usefulness of the items players might receive.

But you should pitch the idea in one of the RE2R modding Discords! I bet people would find the idea interesting, or be able to point you to something similar.

(Worth noting that your long run scenario of players playing Leon and Claire together is sorta possible with this multiworld though. Archipelago lets people play randomizers in the same "universe", so to speak, so you could have multiple people playing multiple RE2R scenarios and sharing items back and forth. Just not via a shared item box.)

**Comment by RaiRaiTheRaichu** [comment]
I gotcha, I wasn't sure on the multiworld aspect or how that worked exactly. 

You mentioned sharing items "back and forth", but how is that handed instead then, a in case like for RE2R currently?

**Comment by FuzzyGamesOn** [comment]
Yeah, exactly! In a standard randomizer, all of your items are randomized across the locations they came from. In a multiworld randomizer, all of your items are randomized with all of every other player's items across all of the locations from their worlds and yours. So instead of your items just being in your game, they can be in other people's games in the same generated multiworld. So you can have a Leon and a Claire in the same multi, and might end up with Claire's Heart Key being found in Leon's Record Room in RPD and, when it's found, it's sent to the Claire player permanently.

**Comment by FuzzyGamesOn** [comment]
> Finally: if I went ahead and added the feature myself, would you be open to a PR with the functionality, or would you prefer it staying as a separate mod entirely?

You should totally look at working out that feature yourself in a separate mod. Even if I can't see how it would work out with this randomizer mod that's specifically designed for AP multiworlds, there's probably some value in having a mod like that around in general. And no reason why we couldn't incorporate it if it does work out. Should be able to detect which mods are installed, so we could just have an integration if it makes sense to have one. :smiley: 

For client mod things, you'll likely want to check out the repo that has the REF code in it instead of this one: https://github.com/FuzzyGamesOn/RE2R_AP_Client

**Comment by FuzzyGamesOn** [comment]
Been about a month on this and no updates, so closing. If you have any further issues, feel free to open a new issue (and reference this one if needed).
